
/**
 * Auto-generated Component Utilities
 * Generated by Design System CLI v1.0.0
 */

// Component factory functions
export const createComponent = (type: 'badge' | 'button' | 'input') => {
  const baseConfig = {
    badge: {
      baseClasses: 'inline-flex items-center font-medium rounded-full transition-colors duration-200',
      variants: generateColorVariants(['primary', 'success', 'warning', 'danger'], 'soft'),
      sizes: COMPONENT_SIZE_PRESETS.badge
    },
    button: {
      baseClasses: BASE_INTERACTIVE_CLASSES + ' rounded-md font-medium',
      variants: generateColorVariants(['primary', 'success', 'warning', 'danger'], 'solid'),
      sizes: COMPONENT_SIZE_PRESETS.button
    },
    input: {
      baseClasses: 'block w-full rounded-md border ' + BASE_INTERACTIVE_CLASSES,
      variants: {
        default: VALIDATION_STATES.default,
        error: VALIDATION_STATES.invalid,
        success: VALIDATION_STATES.valid
      },
      sizes: COMPONENT_SIZE_PRESETS.input
    }
  };

  return baseConfig[type];
};

// Automated component class generator
export const generateComponentClasses = (
  type: 'badge' | 'button' | 'input',
  variant: string,
  size: string,
  additionalClasses: string[] = []
) => {
  const config = createComponent(type);
  return classNames(
    config.baseClasses,
    config.variants[variant] || config.variants.default,
    config.sizes[size] || config.sizes.md,
    ...additionalClasses
  );
};
