
/**
 * Auto-generated Size Utilities
 * Generated by Design System CLI v1.0.0
 */

// Component size presets
export const COMPONENT_SIZE_PRESETS = {
  button: {
    xs: createSizeClasses('xs', { 
      customPadding: { xs: 'px-2.5 py-1.5' },
      customText: { xs: 'text-xs' }
    }),
    sm: createSizeClasses('sm', { 
      customPadding: { sm: 'px-3 py-2' },
      customText: { sm: 'text-sm' }
    }),
    md: createSizeClasses('md', { 
      customPadding: { md: 'px-4 py-2.5' },
      customText: { md: 'text-sm' }
    }),
    lg: createSizeClasses('lg', { 
      customPadding: { lg: 'px-6 py-3' },
      customText: { lg: 'text-base' }
    }),
    xl: createSizeClasses('xl', { 
      customPadding: { xl: 'px-8 py-4' },
      customText: { xl: 'text-lg' }
    })
  },
  input: {
    sm: createSizeClasses('sm', {
      customPadding: { sm: 'px-3 py-2' },
      customText: { sm: 'text-sm' }
    }),
    md: createSizeClasses('md', {
      customPadding: { md: 'px-4 py-2.5' },
      customText: { md: 'text-sm' }
    }),
    lg: createSizeClasses('lg', {
      customPadding: { lg: 'px-4 py-3' },
      customText: { lg: 'text-base' }
    })
  },
  badge: {
    sm: createSizeClasses('sm', {
      customPadding: { sm: 'px-2 py-0.5' },
      customText: { sm: 'text-sm' }
    }),
    md: createSizeClasses('md', {
      customPadding: { md: 'px-2.5 py-0.5' },
      customText: { md: 'text-sm' }
    }),
    lg: createSizeClasses('lg', {
      customPadding: { lg: 'px-3 py-1' },
      customText: { lg: 'text-base' }
    })
  }
};

// Dynamic size class generator
export const generateSizeClasses = (component: 'button' | 'input' | 'badge', size: string) => {
  return COMPONENT_SIZE_PRESETS[component]?.[size] || COMPONENT_SIZE_PRESETS[component].md;
};
