name: Validate Metrics

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-metrics:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build library
      run: npm run build:lib
    
    - name: Generate fresh metrics
      run: npm run generate:metrics
    
    - name: Validate metrics
      run: npm run validate:metrics
    
    - name: Check if metrics are up to date
      run: |
        if git diff --exit-code demo/utils/metrics.ts metrics.json; then
          echo "✅ Metrics are up to date"
        else
          echo "❌ Metrics are outdated. Please run 'npm run generate:metrics' and commit the changes."
          echo "Changed files:"
          git diff --name-only demo/utils/metrics.ts metrics.json
          exit 1
        fi
