name: Sync Documentation to Wiki

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Sync documentation files
        run: |
          # Create wiki directory if it doesn't exist
          mkdir -p wiki
          
          # Copy main README as Home page
          cp README.md wiki/Home.md
          
          # Copy all documentation files with new names
          cp docs/design-tokens.md wiki/Design-Tokens.md
          cp docs/implementation-guide.md wiki/Implementation-Guide.md
          cp docs/github-pages-setup.md wiki/GitHub-Pages-Setup.md
          
          # Create a comprehensive index page
          cat > wiki/Documentation-Index.md << 'EOF'
          # Documentation Index
          
          Welcome to the React MFE Shell documentation! This wiki contains comprehensive guides and references for using and extending the design system.
          
          ## Main Documentation
          
          - **[Home](Home)** - Project overview and quick start
          - **[Implementation Guide](Implementation-Guide)** - Detailed implementation instructions
          - **[Design Tokens](Design-Tokens)** - Comprehensive design token documentation
          - **[GitHub Pages Setup](GitHub-Pages-Setup)** - Demo deployment guide
          
          ## Quick Links
          
          ### Getting Started
          ```bash
          # Install in your project
          npm install @jonmatum/react-mfe-shell
          
          # Or clone for development
          git clone https://github.com/jonmatum/react-mfe-shell.git
          cd react-mfe-shell
          npm install
          npm run dev
          ```
          
          ### Design System Usage
          ```tsx
          import { 
            SettingsProvider, 
            Button, 
            Input, 
            Badge,
            tokens 
          } from '@jonmatum/react-mfe-shell';
          
          function App() {
            return (
              <SettingsProvider>
                <Button variant="primary">Hello World</Button>
              </SettingsProvider>
            );
          }
          ```
          
          ### Development Commands
          ```bash
          npm run dev              # Start development server
          npm run build:lib        # Build library
          npm run build:demo       # Build demo
          npm run test:run         # Run tests
          npm run lint             # Lint code
          ```
          
          ## Live Demo
          
          **[View Interactive Demo](https://jonmatum.github.io/react-mfe-shell/)**
          
          ## Additional Resources
          
          - [GitHub Repository](https://github.com/jonmatum/react-mfe-shell)
          - [Issues & Bug Reports](https://github.com/jonmatum/react-mfe-shell/issues)
          - [Contributing Guidelines](https://github.com/jonmatum/react-mfe-shell/blob/main/CONTRIBUTING.md)
          - [npm Package](https://www.npmjs.com/package/@jonmatum/react-mfe-shell)
          
          ---
          
          *Last updated: $(date)*
          *Auto-synced from repository documentation*
          EOF
          
          # Create sidebar navigation
          cat > wiki/_Sidebar.md << 'EOF'
          ## Documentation
          
          **Getting Started**
          - [Home](Home)
          - [Implementation Guide](Implementation-Guide)
          
          **Design System**
          - [Design Tokens](Design-Tokens)
          - [Live Demo](https://jonmatum.github.io/react-mfe-shell/)
          
          **Deployment**
          - [GitHub Pages Setup](GitHub-Pages-Setup)
          
          **Reference**
          - [Documentation Index](Documentation-Index)
          
          ---
          
          **Quick Install**
          ```bash
          npm install @jonmatum/react-mfe-shell
          ```
          EOF

      - name: Commit and push wiki changes
        run: |
          cd wiki
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all changes
          git add .
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: sync documentation from main repository
            
            Auto-sync triggered by commit: ${{ github.sha }}
            Updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            git push
          fi
